menu_index:
    path:     /
    defaults: { _controller: "CantineBundle:menu:index" }
    methods:  GET

menu_show:
    path:     /{id}/show
    defaults: { _controller: "CantineBundle:menu:show" }
    methods:  GET

menu_new:
    path:     /new
    defaults: { _controller: "CantineBundle:menu:new" }
    methods:  [GET, POST]

menu_edit:
    path:     /{id}/edit
    defaults: { _controller: "CantineBundle:menu:edit" }
    methods:  [GET, POST]

menu_delete:
    path:     /{id}/delete
    defaults: { _controller: "CantineBundle:menu:delete" }
    methods:  DELETE
